.dibsJob: &dibsJob
  image: docker:stable
  services:
    - name: docker:dind
      command:
        - "--experimental"
  variables:
    DOCKER_HOST: tcp://docker:2375/
  before_script:
    # Install curl and tar
    - apk add -u curl tar
    # Install qemu-user-static
    - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    # Install buildx
    - curl -Lo /tmp/docker-buildx https://github.com/docker/buildx/releases/download/v0.3.1/buildx-v0.3.1.linux-amd64
    - mkdir -p ~/.docker/cli-plugins/
    - install /tmp/docker-buildx ~/.docker/cli-plugins
    - docker buildx create --name dibs
    - docker buildx use dibs
    - docker buildx inspect --bootstrap
    # Install Helm
    - curl -L https://get.helm.sh/helm-v3.1.1-linux-amd64.tar.gz | tar -zvxf - linux-amd64/helm -O >/tmp/helm
    - install /tmp/helm /usr/local/bin
    # Install ghr
    - curl -L https://github.com/tcnksm/ghr/releases/download/v0.13.0/ghr_v0.13.0_linux_amd64.tar.gz | tar -zvxf - ghr_v0.13.0_linux_amd64/ghr
    - install ghr_v0.13.0_linux_amd64/ghr /usr/local/bin
    # Install Chart Releaser
    - curl -L https://github.com/helm/chart-releaser/releases/download/v0.2.3/chart-releaser_0.2.3_linux_amd64.tar.gz | tar -zvxf - cr
    - install cr /usr/local/bin
    # Install dibs
    - curl -Lo /tmp/dibs https://github.com/pojntfx/dibs/releases/latest/download/dibs-linux-amd64
    - install /tmp/dibs /usr/local/bin
    # Login to Docker Hub
    - docker login ${DOCKER_REGISTRY} --username ${DOCKER_USERNAME} --password ${DOCKER_PASSWORD}

stages:
  # Unit tests
  - supernoded:unitTest
  - edged:unitTest
  - supernodectl:unitTest
  - edgectl:unitTest
  # Integration tests
  - supernoded:integrationTest
  - edged:integrationTest
  - supernodectl:integrationTest
  - edgectl:integrationTest
  # Build and push images
  - supernoded:buildAndPushImage
  - edged:buildAndPushImage
  # Build and push manifest and binaries
  - supernoded:buildAndPushManifestAndBinaries
  - edged:buildAndPushManifestAndBinaries
  # Build and push binaries
  - supernodectl:buildAndPushBinaries
  - edgectl:buildAndPushBinaries
  # Chart integration tests
  - supernoded:chartIntegrationTest
  - edged:chartIntegrationTest
  # Build and push charts
  - supernoded:buildAndPushChart
  - edged:buildAndPushChart

# Unit tests
supernoded:unitTestAMD64:
  <<: *dibsJob
  stage: supernoded:unitTest
  script:
    - dibs -unitTests -target supernoded-linux -platform linux/amd64 -docker
supernoded:unitTestARM64:
  <<: *dibsJob
  stage: supernoded:unitTest
  script:
    - dibs -unitTests -target supernoded-linux -platform linux/arm64 -docker

supernodectl:unitTestAMD64:
  <<: *dibsJob
  stage: supernodectl:unitTest
  script:
    - dibs -unitTests -target supernodectl-linux -platform linux/amd64 -docker
supernodectl:unitTestARM64:
  <<: *dibsJob
  stage: supernodectl:unitTest
  script:
    - dibs -unitTests -target supernodectl-linux -platform linux/arm64 -docker

edged:unitTestAMD64:
  <<: *dibsJob
  stage: edged:unitTest
  script:
    - dibs -unitTests -target edged-linux -platform linux/amd64 -docker
edged:unitTestARM64:
  <<: *dibsJob
  stage: edged:unitTest
  script:
    - dibs -unitTests -target edged-linux -platform linux/arm64 -docker

edgectl:unitTestAMD64:
  <<: *dibsJob
  stage: edgectl:unitTest
  script:
    - dibs -unitTests -target edgectl-linux -platform linux/amd64 -docker
edgectl:unitTestARM64:
  <<: *dibsJob
  stage: edgectl:unitTest
  script:
    - dibs -unitTests -target edgectl-linux -platform linux/arm64 -docker

# Integration tests
supernoded:integrationTestAMD64:
  <<: *dibsJob
  stage: supernoded:integrationTest
  script:
    - dibs -integrationTests -target supernoded-linux -platform linux/amd64 -docker
supernoded:integrationTestARM64:
  <<: *dibsJob
  stage: supernoded:integrationTest
  script:
    - dibs -integrationTests -target supernoded-linux -platform linux/arm64 -docker

supernodectl:integrationTestAMD64:
  <<: *dibsJob
  stage: supernodectl:integrationTest
  script:
    - dibs -integrationTests -target supernodectl-linux -platform linux/amd64 -docker
supernodectl:integrationTestARM64:
  <<: *dibsJob
  stage: supernodectl:integrationTest
  script:
    - dibs -integrationTests -target supernodectl-linux -platform linux/arm64 -docker

# Image tests
# amd64 is disabled for now due to a GitLab bug where it does not exit after being run
#supernoded:imageTestsAMD64:
#  <<: *dibsJob
#  stage: supernoded:integrationTest
#  script:
#    - dibs -buildImage -target supernoded-linux -platform linux/amd64
#    - dibs -imageTests -target supernoded-linux -platform linux/amd64
supernoded:imageTestsARM64:
  <<: *dibsJob
  stage: supernoded:integrationTest
  script:
    - dibs -buildImage -target supernoded-linux -platform linux/arm64
    - dibs -imageTests -target supernoded-linux -platform linux/arm64

edged:integrationTestAMD64:
  <<: *dibsJob
  stage: edged:integrationTest
  script:
    - dibs -integrationTests -target edged-linux -platform linux/amd64 -docker
edged:integrationTestARM64:
  <<: *dibsJob
  stage: edged:integrationTest
  script:
    - dibs -integrationTests -target edged-linux -platform linux/arm64 -docker

edgectl:integrationTestAMD64:
  <<: *dibsJob
  stage: edgectl:integrationTest
  script:
    - dibs -integrationTests -target edgectl-linux -platform linux/amd64 -docker
edgectl:integrationTestARM64:
  <<: *dibsJob
  stage: edgectl:integrationTest
  script:
    - dibs -integrationTests -target edgectl-linux -platform linux/arm64 -docker

# Image tests
# amd64 is disabled for now due to a GitLab bug where it does not exit after being run
#edged:imageTestsAMD64:
#  <<: *dibsJob
#  stage: edged:integrationTest
#  script:
#    - dibs -buildImage -target edged-linux -platform linux/amd64
#    - dibs -imageTests -target edged-linux -platform linux/amd64
edged:imageTestsARM64:
  <<: *dibsJob
  stage: edged:integrationTest
  script:
    - dibs -buildImage -target edged-linux -platform linux/arm64
    - dibs -imageTests -target edged-linux -platform linux/arm64

# Build and push image
supernoded:buildAndPushImageAMD64:
  <<: *dibsJob
  stage: supernoded:buildAndPushImage
  script:
    - dibs -buildImage -target supernoded-linux -platform linux/amd64
    - dibs -pushImage -target supernoded-linux -platform linux/amd64
  only:
    - tags
supernoded:buildAndPushImageARM64:
  <<: *dibsJob
  stage: supernoded:buildAndPushImage
  script:
    - dibs -buildImage -target supernoded-linux -platform linux/arm64
    - dibs -pushImage -target supernoded-linux -platform linux/arm64
  only:
    - tags

edged:buildAndPushImageAMD64:
  <<: *dibsJob
  stage: edged:buildAndPushImage
  script:
    - dibs -buildImage -target edged-linux -platform linux/amd64
    - dibs -pushImage -target edged-linux -platform linux/amd64
  only:
    - tags
edged:buildAndPushImageARM64:
  <<: *dibsJob
  stage: edged:buildAndPushImage
  script:
    - dibs -buildImage -target edged-linux -platform linux/arm64
    - dibs -pushImage -target edged-linux -platform linux/arm64
  only:
    - tags

# Build and push manifest
supernoded:buildAndPushManifest:
  <<: *dibsJob
  stage: supernoded:buildAndPushManifestAndBinaries
  script:
    - dibs -buildManifest -target supernoded-linux
    - dibs -pushManifest -target supernoded-linux
  only:
    - tags

edged:buildAndPushManifest:
  <<: *dibsJob
  stage: edged:buildAndPushManifestAndBinaries
  script:
    - dibs -buildManifest -target edged-linux
    - dibs -pushManifest -target edged-linux
  only:
    - tags

# Build and push binaries
supernoded:buildAndPushBinariesAMD64:
  <<: *dibsJob
  stage: supernoded:buildAndPushManifestAndBinaries
  script:
    - dibs -build -target supernoded-linux -platform linux/amd64 -docker
    - dibs -pushBinary -target supernoded-linux -platform linux/amd64
  artifacts:
    name: supernoded-binaries-amd64
    paths:
      - .bin/binaries/supernoded
    expire_in: 1 month
  only:
    - tags
supernoded:buildAndPushBinariesARM64:
  <<: *dibsJob
  stage: supernoded:buildAndPushManifestAndBinaries
  script:
    - dibs -build -target supernoded-linux -platform linux/arm64 -docker
    - dibs -pushBinary -target supernoded-linux -platform linux/arm64
  artifacts:
    name: supernoded-binaries-arm64
    paths:
      - .bin/binaries/supernoded
    expire_in: 1 month
  only:
    - tags

supernodectl:buildAndPushBinariesAMD64:
  <<: *dibsJob
  stage: supernodectl:buildAndPushBinaries
  script:
    - dibs -build -target supernodectl-linux -platform linux/amd64 -docker
    - dibs -pushBinary -target supernodectl-linux -platform linux/amd64
  artifacts:
    name: supernodectl-binaries-amd64
    paths:
      - .bin/binaries/supernodectl
    expire_in: 1 month
  only:
    - tags
supernodectl:buildAndPushBinariesARM64:
  <<: *dibsJob
  stage: supernodectl:buildAndPushBinaries
  script:
    - dibs -build -target supernodectl-linux -platform linux/arm64 -docker
    - dibs -pushBinary -target supernodectl-linux -platform linux/arm64
  artifacts:
    name: supernodectl-binaries-arm64
    paths:
      - .bin/binaries/supernodectl
    expire_in: 1 month
  only:
    - tags

edged:buildAndPushBinariesAMD64:
  <<: *dibsJob
  stage: edged:buildAndPushManifestAndBinaries
  script:
    - dibs -build -target edged-linux -platform linux/amd64 -docker
    - dibs -pushBinary -target edged-linux -platform linux/amd64
  artifacts:
    name: edged-binaries-amd64
    paths:
      - .bin/binaries/edged
    expire_in: 1 month
  only:
    - tags
edged:buildAndPushBinariesARM64:
  <<: *dibsJob
  stage: edged:buildAndPushManifestAndBinaries
  script:
    - dibs -build -target edged-linux -platform linux/arm64 -docker
    - dibs -pushBinary -target edged-linux -platform linux/arm64
  artifacts:
    name: edged-binaries-arm64
    paths:
      - .bin/binaries/edged
    expire_in: 1 month
  only:
    - tags

edgectl:buildAndPushBinariesAMD64:
  <<: *dibsJob
  stage: edgectl:buildAndPushBinaries
  script:
    - dibs -build -target edgectl-linux -platform linux/amd64 -docker
    - dibs -pushBinary -target edgectl-linux -platform linux/amd64
  artifacts:
    name: edgectl-binaries-amd64
    paths:
      - .bin/binaries/edgectl
    expire_in: 1 month
  only:
    - tags
edgectl:buildAndPushBinariesARM64:
  <<: *dibsJob
  stage: edgectl:buildAndPushBinaries
  script:
    - dibs -build -target edgectl-linux -platform linux/arm64 -docker
    - dibs -pushBinary -target edgectl-linux -platform linux/arm64
  artifacts:
    name: edgectl-binaries-arm64
    paths:
      - .bin/binaries/edgectl
    expire_in: 1 month
  only:
    - tags

# Chart tests
supernoded:chartTestsAMD64:
  <<: *dibsJob
  stage: supernoded:chartIntegrationTest
  script:
    - dibs -chartTests -target supernoded-linux -platform linux/amd64 -docker
  only:
    - tags
supernoded:chartTestsARM64:
  <<: *dibsJob
  stage: supernoded:chartIntegrationTest
  script:
    - dibs -chartTests -target supernoded-linux -platform linux/arm64 -docker
  only:
    - tags

edged:chartTestsAMD64:
  <<: *dibsJob
  stage: edged:chartIntegrationTest
  script:
    - dibs -chartTests -target edged-linux -platform linux/amd64 -docker
  only:
    - tags
edged:chartTestsARM64:
  <<: *dibsJob
  stage: edged:chartIntegrationTest
  script:
    - dibs -chartTests -target edged-linux -platform linux/arm64 -docker
  only:
    - tags

# Build and push chart
supernoded:buildAndPushChart:
  <<: *dibsJob
  stage: supernoded:buildAndPushChart
  script:
    - dibs -buildChart -target supernoded-linux
    - dibs -pushChart -target supernoded-linux
  artifacts:
    name: supernoded-chart
    paths:
      - .bin/chart/supernoded
    expire_in: 1 month
  only:
    - tags

edged:buildAndPushChart:
  <<: *dibsJob
  stage: edged:buildAndPushChart
  script:
    - dibs -buildChart -target edged-linux
    - dibs -pushChart -target edged-linux
  artifacts:
    name: edged-chart
    paths:
      - .bin/chart/edged
    expire_in: 1 month
  only:
    - tags
