apiVersion: skaffold/v1
kind: Config
metadata:
  name: supernoded
profiles:
  - name: supernoded
    build:
      artifacts:
        - image: pojntfx/supernoded
          context: .
          docker:
            dockerfile: Dockerfile.supernoded
            buildArgs:
              DIBS_TARGET: supernoded-linux
      local:
        useBuildkit: true
    deploy:
      helm:
        releases:
          - name: supernoded
            chartPath: charts/supernoded
            values:
              meta.image: pojntfx/supernoded
  - name: supernoded-dev
    build:
      artifacts:
        - image: pojntfx/supernoded-dev
          context: .
          docker:
            dockerfile: Dockerfile.dev
            buildArgs:
              DIBS_TARGET: supernoded-linux
          sync:
            infer:
              - "**/*" # Re-deploy manually to apply k8s changes
      local:
        useBuildkit: true
    deploy:
      helm:
        releases:
          - name: supernoded-dev
            chartPath: charts/supernoded
            values:
              meta.image: pojntfx/supernoded-dev
            setValues:
              meta.dev: true
              meta.target: supernoded-linux
            setValueTemplates:
              meta.platform: "{{ .TARGETPLATFORM }}"
              meta.debug: "{{ .DIBS_DEBUG }}"
  - name: edged
    build:
      artifacts:
        - image: pojntfx/edged
          context: .
          docker:
            dockerfile: Dockerfile.edged
            buildArgs:
              DIBS_TARGET: edged-linux
      local:
        useBuildkit: true
    deploy:
      helm:
        releases:
          - name: edged
            chartPath: charts/edged
            values:
              meta.image: pojntfx/edged
  - name: edged-dev
    build:
      artifacts:
        - image: pojntfx/edged-dev
          context: .
          docker:
            dockerfile: Dockerfile.dev
            buildArgs:
              DIBS_TARGET: edged-linux
          sync:
            infer:
              - "**/*" # Re-deploy manually to apply k8s changes
      local:
        useBuildkit: true
    deploy:
      helm:
        releases:
          - name: edged-dev
            chartPath: charts/edged
            values:
              meta.image: pojntfx/edged-dev
            setValues:
              meta.dev: true
              meta.target: edged-linux
            setValueTemplates:
              meta.platform: "{{ .TARGETPLATFORM }}"
              meta.debug: "{{ .DIBS_DEBUG }}"
