apiVersion: v1
name: edged
version: 0.0.1
description: An n2n edge management daemon.
type: application
home: https://pojntfx.github.io/gon2n/
sources:
  - git@github.com:pojntfx/gon2n.git
maintainers:
  - name: Felicitas Pojtinger
    email: felicitas@pojtinger.com
    url: https://felicitas.pojtinger.com
appVersion: 0.0.1
