name: dibs CI

on: [push]

jobs:
  dibs-amd64:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: |
          echo $'{\n    "experimental": true\n}' | sudo tee /etc/docker/daemon.json
      - run: sudo service docker restart
      - run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      - run: curl -Lo /tmp/docker-buildx https://github.com/docker/buildx/releases/download/v0.5.1/buildx-v0.5.1.linux-amd64
      - run: mkdir -p ~/.docker/cli-plugins/
      - run: install /tmp/docker-buildx ~/.docker/cli-plugins
      - run: docker buildx create --name dibs
      - run: docker buildx use dibs
      - run: docker buildx inspect --bootstrap
      - run: curl -L https://get.helm.sh/helm-v3.1.1-linux-amd64.tar.gz | tar -zvxf - linux-amd64/helm -O >/tmp/helm
      - run: sudo install /tmp/helm /usr/local/bin
      - run: curl -L https://github.com/tcnksm/ghr/releases/download/v0.13.0/ghr_v0.13.0_linux_amd64.tar.gz | tar -zvxf - ghr_v0.13.0_linux_amd64/ghr
      - run: sudo install ghr_v0.13.0_linux_amd64/ghr /usr/local/bin
      - run: curl -L https://github.com/helm/chart-releaser/releases/download/v0.2.3/chart-releaser_0.2.3_linux_amd64.tar.gz | tar -zvxf - cr
      - run: sudo install cr /usr/local/bin
      - run: curl -Lo /tmp/dibs https://nx904.your-storageshare.de/s/ZWxkmmQW37fHt9J/download
      - run: sudo install /tmp/dibs /usr/local/bin
      - run: docker login ${DOCKER_REGISTRY} --username ${DOCKER_USERNAME} --password ${DOCKER_PASSWORD}
        env:
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: dibs -unitTests -target linux -platform linux/amd64 -docker
      - run: dibs -integrationTests -target linux -platform linux/amd64 -docker
      - run: dibs -buildImage -target linux -platform linux/amd64
      - run: dibs -imageTests -target linux -platform linux/amd64
      - run: dibs -buildImage -target linux -platform linux/amd64
      - run: dibs -pushImage -target linux -platform linux/amd64
        if: startsWith(github.ref, 'refs/tags/v')
      - run: dibs -buildManifest -target linux
      - run: dibs -pushManifest -target linux
        if: startsWith(github.ref, 'refs/tags/v')
      - run: dibs -build -target linux -platform linux/amd64 -docker
      - run: dibs -pushBinary -target linux -platform linux/amd64
        env:
          DIBS_GITHUB_USER_NAME: ${{ secrets.DIBS_GITHUB_USER_NAME }}
          DIBS_GITHUB_TOKEN: ${{ secrets.DIBS_GITHUB_TOKEN }}
          DIBS_GITHUB_REPOSITORY: ${{ secrets.DIBS_GITHUB_REPOSITORY }}
        if: startsWith(github.ref, 'refs/tags/v')
      - run: dibs -chartTests -target linux -platform linux/amd64 -docker
      - run: dibs -buildChart -target linux
      - run: dibs -pushChart -target linux
        env:
          DIBS_GITHUB_USER_NAME: ${{ secrets.DIBS_GITHUB_USER_NAME }}
          DIBS_GITHUB_TOKEN: ${{ secrets.DIBS_GITHUB_TOKEN }}
          DIBS_GITHUB_REPOSITORY: ${{ secrets.DIBS_GITHUB_REPOSITORY }}
          DIBS_GITHUB_REPOSITORY_NAME: ${{ secrets.DIBS_GITHUB_REPOSITORY_NAME }}
          DIBS_GITHUB_REPOSITORY_URL: ${{ secrets.DIBS_GITHUB_REPOSITORY_URL }}
          DIBS_GITHUB_PAGES_URL: ${{ secrets.DIBS_GITHUB_PAGES_URL }}
          DIBS_GIT_USER_NAME: ${{ secrets.DIBS_GIT_USER_NAME }}
          DIBS_GIT_USER_EMAIL: ${{ secrets.DIBS_GIT_USER_EMAIL }}
          DIBS_GIT_COMMIT_MESSAGE: ${{ secrets.DIBS_GIT_COMMIT_MESSAGE }}
        if: startsWith(github.ref, 'refs/tags/v')
