name: make CI

on: [push, pull_request]

jobs:
  make:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.15.7" # The Go version to download (if necessary) and use.
      - name: Install Wine
        run: sudo apt install -y wine-development
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
      - name: Install Go protoc plugin
        run: go get google.golang.org/protobuf/cmd/protoc-gen-go google.golang.org/grpc/cmd/protoc-gen-go-grpc
      - uses: actions/checkout@v2
      - name: Build with make
        run: make -j$(nproc)
      - name: Run tests
        run: make test -j$(nproc)
      - name: Publish to GitHub releases
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            out/*
      - name: Publish tagged release to GitHub releases
        if: startsWith(github.ref, 'refs/tags/v')
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            out/*
